### ISSUE TITLE
we don’t need spring-cloud-starter-bootstrap anymore.

### ISSUE THREAD

**Issue by b19g3r** [uncarbon97/helio-starters#27]
hello

As described in the Spring Cloud Config documentation, we don’t need spring-cloud-starter-bootstrap anymore.

[Document link](https://docs.spring.io/spring-cloud-config/reference/client.html#config-first-bootstrap)

No `bootstrap.yml` is needed — `application.yml` suffices.

https://github.com/uncarbon97/helio-starters/blob/e083af8eb10c4f22c996832e32cd4ebd3c45f4a8/helio-starter-cloud/pom.xml#L29-L32

For example:

```
# application.yml
spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      username: nacos
      password: nacos
      config:
        server-addr: xxx
        file-extension: yml
  config:
    import:
      - nacos:application.${spring.cloud.nacos.config.file-extension}?refreshEnabled=true
```
